### ISSUE TITLE
关于bf1chs （flamethrower）提出功能改进

### ISSUE THREAD

**Issue by Jerry114514** [zyf722/flamethrower#2]
是否可以将检测font-family的功能整合到工具内，这样在替换字体时可以更方便

**Comment by zyf722** [comment]
已在 88b24d8 中加入，下个发行版会正式发布。

**Comment by zyf722** [comment]
BF1CHS [v0.4.0](https://github.com/zyf722/flamethrower/releases/tag/v0.1.4) 已加入。

如果存在后续问题请重新开启。
