### ISSUE TITLE
码表大小好像对不上

### ISSUE THREAD

**Issue by ChestnutKCN** [zyf722/flamethrower#3]
![QQ截图20240218132419](https://github.com/zyf722/flamethrower/assets/94287289/73de417c-a7ec-4a2d-b19f-da1d0b062b65)

**Comment by ChestnutKCN** [comment]
还有个问题就是，我把CHS生成的chunk导入寒霜编辑器时，如果不改chunksize会导致使用mod时一些文字显示为〿，改了chunksize又会导致导出mod时出现错误提示“未将对象引用设置到对象的实例”

**Comment by zyf722** [comment]
OK，待我有空时尝试复现一下。

**Comment by zyf722** [comment]
有关码表大小问题 BF1CHS [v0.4.0](https://github.com/zyf722/flamethrower/releases/tag/v0.1.4) 已修复，如果存在后续问题请重新开启。

导入寒霜编辑器时必须修改对应的 ChunkSize，至于出现的错误应该不是 BF1CHS 导致的行为，我这边可以正常导出。有进一步的信息吗？
