### ISSUE TITLE
希望可以把flamethrower和bf1chs分成两个repo

### ISSUE THREAD

**Issue by shoushou1106** [zyf722/flamethrower#6]
希望可以把flamethrower和bf1chs分成两个repo，(应该)可以让release不会那么混乱，也更好分清版本。之后flamethrower建议以PyPI包的形式发布

**Comment by zyf722** [comment]
确实有这个必要，择时完成。

编辑：之后应该会迁移到 [BF1CHS](https://github.com/BF1CHS) 组织名下分成两个仓库，迁移完成后本仓库将归档。

**Comment by zyf722** [comment]
迁移已经完成，本仓库及 BF1CHS 工具箱源码已分别迁移至 [BF1CHS/flammenwerfer](https://github.com/BF1CHS/flammenwerfer) 及 [BF1CHS/bf1chs](https://github.com/BF1CHS/bf1chs)，此处不再维护。

`flammenwerfer` 已作为 PyPI 包发布。
